[tool.black]
target-version = ['py313']
skip-string-normalization = 1
line-length = 120

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120
profile = "black"
force_sort_within_sections = true
combine_as_imports = true

